---
title: "Reviews"
format: html
---

# Podcast Review: The Next Industrial Revolution is Industrial AI

To get ready for class 2, I listened to a recent Dataframed podcast episode called “The Next Industrial Revolution is Industrial AI” with Barbara Humpton (CEO, Siemens USA) and Olympia Brikis (Director of Industrial AI at Siemens USA).

The general theme was industrial AI versus consumer AI. Consumer AI is found in ordinary life, like a recommendation feature or a chatbot on a website. It doesn't matter when it makes mistakes because there is little risk and is not as strict. Industrial AI, on the other hand, runs inside factories, power generation, and other mechanical processes. It has to be extremely safe and trustworthy because little mistakes can destroy a factory line or pose safety risks.

What is most interesting is that industrial AI is being used not to replace humans but to help them. The speakers explained how technologies like predictive maintenance, computer-vision quality checks, and digital twins (virtual copies of a manufacturing line) allow factories to work better. For example, a digital twin can simulate a new line before it's ever built, cutting setup time from years to months. A different story illustrated how computer vision systems of today inspect each car door in real-time as opposed to spot checks, which provides assurance of quality at a much greater scale. The show also brought out the "human + machine" partnership. Instead of laying off individuals, companies have the same workers but use them more efficiently. Workers depart from monotonous manual tasks, like inspecting every part manually, to exceptions and process optimization. I liked this because it showed a better future for work, especially in light of the specter that AI is going to take people's jobs away. AI as a means to upskill, not fear.

Although, I would have liked to see more numbers and metrics. They mentioned timelines and substantial productivity gains, but it would have been nice to see specific metrics. I also would have liked to hear more about concerns like safety risks, data quality, or model learning in extreme factory environments.

Overall, it is a great primer for those who want to know how AI is already changing manufacturing. It is especially helpful for plant managers, engineers, and policymakers thinking about workforce development. For me, and especially for one who is open to adopting AI as new technology, the most important takeaway is that industrial AI is not about substituting humans, but it's about humans and AI working together to make industries smarter, faster, and safer.
